### ISSUE TITLE
About the anatomical models

### ISSUE THREAD

**Issue by DLwbm123** [adgilbert/data-generation#1]
Hi! Thanks for sharing this fantastic project. Could you please upload the anatomical models? Thanks!

**Comment by adgilbert** [comment]
Hello, The models will be released soon, following the publication of a paper describing them. In the meantime you can check out [this paper](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0235145) for a repository of similar models.

**Comment by gungui98** [comment]
@adgilbert Hi, I wonder if there is any update on release the model yet?

**Comment by adgilbert** [comment]
Hi @DLwbm123  and @gungui98, the anatomical models are available here: https://zenodo.org/record/4590294#.YbfgcdDMLD4

I will add the link to the README. There is one difference between these models and the models we used in the paper. The models used in the paper had a single "pericardium" layer added around the outside of the mesh and that layer is used in some parts of the code.

I will see if my colleague still has the code to add the pericardium readily available, otherwise we can add the model set with pericardium as well.
